apps/noticias/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('listarNoticia/', views.mostrarNoticia.as_view()), #clase
    path('detalle/<int:pk>', views.DetalleNoticias, name='detalle'),
    path('addNoticia/', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditNoticia, name='edit_noticia'),
    #url comentarios
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('comment/add/<int:noticia_id>/', views.add_comment, name='add_comment'),
    path('comment/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('quienes_somos', views.quienes_somos, name='quienes_somos'),
]

apps/noticias/models.py
from django.db import models
from usuarios.models import Usuario

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nombre


class Noticia(models.Model):
    titulo = models.CharField(max_length=250)
    resumen = models.CharField(max_length=100)
    contenido = models.TextField()
    fecha_de_publicacion = models.DateTimeField(auto_now_add=True)
    #para imagen debemos instalar pillow
    imagen = models.ImageField(upload_to= 'noticias')
    categoria_noticia = models.ForeignKey(Categoria, on_delete= models.CASCADE) #SET_NULL
    author = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.titulo
    
class Comment(models.Model):
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=100)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

apps/noticias/forms.py
from django import forms
from .models import Noticia, Comment
from django.forms import ModelForm, TextInput
from django.forms.widgets import TextInput, FileInput, Select


class NoticiaForm(forms.ModelForm):
    
    class Meta:
        model = Noticia
        fields = ['titulo', 'resumen', 'contenido', 'imagen', 'categoria_noticia']
        widgets = {
            'titulo': TextInput(attrs={'class': 'form-control'}),
            'resumen': TextInput(attrs={'class': 'form-control'}),
            'contenido': forms.Textarea(attrs={'class': 'form-control'}),
            'imagen': FileInput(attrs={'class': 'form-control'}),
            'categoria_noticia': Select(attrs={'class': 'form-control'}),
        }


# CREAR COMENTARIOS
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text'] #campos de mi formulario
        exclude = ['author']
        widgets = {
        'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Escribe tu comentario aquí...'}),
    }
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(CommentForm, self).__init__(*args, **kwargs)
        if user:
            self.instance.author = user.username

apps/noticias/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Noticia, Categoria, Comment, Usuario
from django.views.generic.list import ListView #para las vistas clases
from .forms import NoticiaForm, CommentForm
from django.http import HttpResponseForbidden
from django.contrib import messages

# Create your views here.

#VISTA CON FUNCIONES
'''def ListarNoticias(request):
    contexto = {} #diccionario
    id_categoria = request.GET.get("id", None)

    if id_categoria:
        n = Noticia.objects.filter(categoria_noticia = id_categoria)
    else:
        n = Noticia.objects.all() #SELECT * FROM Noticias / lista objetos

    contexto['noticias'] = n

    cat = Categoria.objects.all().order_by('nombre') #ordena por nombre
    contexto['categorias'] = cat

    return render(request, 'noticias/listar.html', contexto)'''

def ListarNoticias(request):
    noticias = Noticia.objects.all()

    # Filtrar por categoría
    categoria = request.GET.get('categoria')
    if categoria:
        noticias = noticias.filter(categoria_noticia=categoria)

    # Filtrar por antigüedad ascendente
    antiguedad_asc = request.GET.get('antiguedad_asc')
    if antiguedad_asc:
        noticias = noticias.order_by('fecha_de_publicacion')

    # Filtrar por antigüedad descendente
    antiguedad_desc = request.GET.get('antiguedad_desc')
    if antiguedad_desc:
        noticias = noticias.order_by('-fecha_de_publicacion')

    # Filtrar por orden alfabético ascendente
    orden_asc = request.GET.get('orden_asc')
    if orden_asc:
        noticias = noticias.order_by('titulo')

    # Filtrar por orden alfabético descendente
    orden_desc = request.GET.get('orden_desc')
    if orden_desc:
        noticias = noticias.order_by('-titulo')

    context = {
        'noticias': noticias,
        'categorias': Categoria.objects.all(),  
    }
    return render(request, 'noticias/listar.html', context)


#VISTA CON CLASES
class mostrarNoticia(ListView):
    model = Noticia
    template_name = 'noticias/listarNoticia.html'

'''def DetalleNoticias(request, pk):
    contexto = {} #diccionario

    n = Noticia.objects.get(pk = pk) # 1 solo objeto

    contexto['noticia'] = n

    return render(request, 'noticias/detalle.html', contexto)
'''

def DetalleNoticias(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)
    comments = noticia.comments.all()

    #BORRAR NOTICIA
    if request.method == 'POST' and 'delete_noticia' in request.POST:
        noticia.delete()
        return redirect('noticias:listar')

    # COMENTARIO
    if request.method == 'POST' and 'add_comment' in request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            noticia = get_object_or_404(Noticia, pk=pk)  # Obtén la noticia aquí
            comment = form.save(commit=False)
            comment.noticia = noticia  # Asigna la noticia obtenida
            comment.author = request.user
            comment.save()
        return redirect('noticias:detalle', pk=pk)
    else:
        form = CommentForm()

    context = {
        'noticia': noticia,
        'comments': comments,
        'form': form,
    }
    return render(request, 'noticias/detalle.html', context)
# BORRAR COMENTARIOS
@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author or comment.staff == request.user.username:
        comment.delete()
    return redirect('noticias:detalle', pk=comment.noticia.pk)

# AÑADIR COMENTARIOS
@login_required
def add_comment(request, noticia_id):
    noticia = get_object_or_404(Noticia, id=noticia_id)
    if request.method == 'POST':
        text = request.POST.get('text')
        author = request.user.username
        # creacion de comentario
        Comment.objects.create(noticia=noticia, author=author, text=text)
    return redirect('noticias:detalle', pk=noticia_id)


# EDITAR COMENTARIOS
@login_required
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    #mensaje de error si no sos el autor
    #if comment.author != request.user.username:
        #messages.error(request, 'No tienes permisos para editar este comentario.')
        #return redirect('noticias:detalle', pk=comment.noticia.pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=comment.noticia.pk)
    else:
        form = CommentForm(instance=comment)

    context = {
        'form': form,
        'comment': comment,
    }
    return render(request, 'noticias/edit_comment.html', context)

@login_required
def AddNoticia(request):
    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES) ##REQUEST FILE PARA LAS IMAGENES
        if form.is_valid():
            noticia = form.save(commit=False)
            noticia.author = request.user #autor de la noticia
            noticia.save()
            return redirect('noticias:listar')
    else:
        form = NoticiaForm()
    
    return render(request, 'noticias/addNoticia.html', {'form': form})

@login_required
def EditNoticia(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)

    # Solo el autor puede editar la noticia
    #if noticia.author != request.user:
        #return HttpResponseForbidden("No tenes permiso para editar esta noticia.")

    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES, instance=noticia)
        if form.is_valid():
            form.save()
            return redirect('noticias:detalle', pk=pk)
    else:
        form = NoticiaForm(instance=noticia)

    context = {
        'form': form,
    }
    return render(request, 'noticias/editNoticia.html', context)

templates/noticias/addNoticia.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOTICIAS{% endblock titulo %}
<head>
    <link rel="stylesheet" href="{% static 'css/listar.css' %}">
</head>
{% block contenido %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form action="" method="POST" enctype="multipart/form-data" class="form-group m-4">
                    <h2>Crea una noticia</h2>
                    <div class="mb-3">
                        {% csrf_token %}
                    
                        {{ form.as_p }}
                    </div>
                    
                    <div class="text-center">
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock contenido %}

templates/noticias/addNoticiaDesglosado.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOTICIAS{% endblock titulo %}

{% block contenido %}
    <h2>Crea una noticia</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <p>
            <label for="{{ form.titulo.id_for_label }}">Titulo:</label>
            {{ form.titulo }}
        </p>
        
        <p>
            <label for="{{ form.resumen.id_for_label }}">Resumen:</label>
            {{ form.resumen }}
        </p>
        
        <p>
            <label for="{{ form.contenido.id_for_label }}">Contenido:</label>
            {{ form.contenido }}
        </p>
        
        <p>
            <label for="{{ form.imagen.id_for_label }}">Imagen:</label>
            {{ form.imagen }}
        </p>
        
        <p>
            <label for="{{ form.categoria_noticia.id_for_label }}">Categoria noticia:</label>
            <select name="{{ form.categoria_noticia.name }}" required id="{{ form.categoria_noticia.id_for_label }}">
                {% for choice in form.categoria_noticia.field.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </p>
        
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}

templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

    <head>
        <link rel="stylesheet" href="{% static 'css/detalle.css' %}">
        <!-- Vendor CSS Files -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
        <link href="vendor/aos/aos.css" rel="stylesheet">
        <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    </head>



    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
        <nav>
          <div class="container">
            <ol>
              <li><a href="{% url 'noticias:listar' %}">Noticias</a></li>
              <li>Blog Details</li>
            </ol>
          </div>
        </nav>
      </div><!-- End Breadcrumbs -->

      <!-- ======= Blog Details Section ======= -->
    <section id="blog" class="blog">
        <div class="container" data-aos="fade-up">
  
          <div class="row g-5">
  
            <div class="col-lg-8">
  
              <article class="blog-details">
  
                <div class="post-img">
                  <img src="{{ noticia.imagen.url }}" alt="" class="img-fluid">
                </div>
  
                <h2 class="title"> {{noticia.titulo}} </h2>
  
                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-details.html"> {{noticia.author}} </a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-details.html"><time datetime="2020-01-01">{{ noticia.fecha_de_publicacion }}</time></a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-details.html">12 Comments</a></li>
                  </ul>
                </div><!-- End meta top -->
  
                <div class="content">
                  <p>
                    {{ noticia.contenido }}
                  </p>
                </div><!-- End post content -->
  
                <div class="meta-bottom">
                  <i class="bi bi-folder"></i>
                  <ul class="cats">
                    <a href="/noticias/categoria/{{ noticia.categoria_noticia }}">{{ noticia.categoria_noticia }}</a>

                  </ul>
              </article><!-- End blog post -->
  

              <!-- ======= Comentarios ======= -->
              <div class="comments">

                <h4 class="comments-count">Comentarios</h4>
                {% for comment in comments %}
                <div id="comment-1" class="comment">
                  <div class="d-flex">
                    <div class="comment-img"><img src="{{user.imagen.url}}" alt=""></div>
                    <div>
                      <h5><a href="">{{ comment.author }}</a> </h5>
                      <time datetime="2020-01-01">{{ comment.created_at }}</time>
                      <p>
                        {{ comment.text }}
                      </p>
                      <form method="POST" action="{% url 'noticias:delete_comment' comment.id %}">
                        {% csrf_token %}
                        {% if comment.author == user.username or user.is_staff or user.is_superuser %}
                            <button class="btn btn-primary" type="submit">Borrar comentario</button>
                            <a href="{% url 'noticias:edit_comment' comment_id=comment.id %}" class="btn btn-primary">Editar comentario</a>
                        {% endif %}
                    </div>
                  </div>
                </div><!-- End comment #1 -->
                {% empty %}
                        <p>No hay comentarios.</p>
                {% endfor %}
                
  
                <div class="reply-form">
                {% if user.is_authenticated %}
                  <h4>Dejanos un comentario</h4>
                  <p>Your email address will not be published. Required fields are marked * </p>
                  <form method="POST" action="{% url 'noticias:add_comment' noticia.pk %}">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col form-group">
                        {{form.as_p}}
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Publicar</button>
  
                  </form>
  
                </div>
                {% else %}
                <p>Debe iniciar sesión para añadir un comentario</p>
                <a href="{% url 'login' %}" class="btn-get-started">LOGIN</a>
                {% endif %}

              </div><!-- End blog comments -->


    <script src="{% static 'js/all.js' %}"></script>
{% endblock contenido %}

templates/noticias/editNoticia.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Editar Noticia{% endblock titulo %}

{% block contenido %}
    <h2>Edita la noticia</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock contenido %}

templates/noticias/edit_comment.html
{% extends 'base.html' %}
{% block contenido %}
    <h2>Editar Comentario</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}

templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}NOTICIAS{% endblock titulo %}
{% block contenido %}
<head>
    <link rel="stylesheet" href="{% static 'css/listar.css' %}">
</head>

        <!-- ======= Breadcrumbs ======= -->
        <div class="breadcrumbs">
            <div class="page-header d-flex align-items-center" style="background-image: url('');">
              <div class="container position-relative">
                <div class="row d-flex justify-content-center">
                  <div class="col-lg-6 text-center">
                    <h2>Blog</h2>
                    <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>
                  </div>
                </div>
              </div>
            </div>
            <nav>
              <div class="container">
                <ol>
                  <li><a href="index.html">Home</a></li>
                  <li>Portal de noticias</li>
                </ol>
              </div>
            </nav>
          </div><!-- End Breadcrumbs -->
      
          <!-- ======= Blog Section ======= -->

          <h2>Aquí están mis noticias</h2> 

          {% if request.user.tipo_usuario == 'Colaborador' or request.user.is_superuser%}
          <div class="">
            <a href="{% url 'noticias:addnoticia' %}" class="btn-get-started">Añadir Noticia</a>
          </div>
          {%endif%}
          
          
          


          
          <div class="submenu ">
            <div class="d-flex align-items-center">
              <button class="btn-get-started">Categorías</button>
              <div class="ml-2 movi">
                <a href="{% url 'noticias:listar' %}" class="texts-buttons text-decoration-none">Todas las noticias</a>
                {% for cat in categorias %}
                  <a class="text-decoration-none" href="?categoria={{ cat.pk }}">{{ cat.nombre }}</a>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="d-flex buttons align-items-center">
            <button class="btn-get-started">Ordenar</button>
              <div class="movi">
                <a href="?antiguedad_asc=1" class="text-decoration-none">Antiguas</a>
                <a  href="?antiguedad_desc=1" class="text-decoration-none">Recientes</a>
                <a href="?orden_asc=1" class="text-decoration-none">A-Z</a>
                <a href="?orden_desc=1" class="text-decoration-none">Z-A</a>
              </div>
          </div>
          </div>



          <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">
        
                <div class="row gy-4 posts-list">
                    {% for noti in noticias %}
                        <div class="col-xl-4 col-md-6">
                            <a href="{% url 'noticias:detalle' noti.pk %}" class="article-link title text-decoration-none" >  <article>
                                    <div class="post-img">
                                        {% if noti.imagen %}
                                            <img src="{{ noti.imagen.url }}" alt="" class="img-fluid">
                                        {% endif %}
                                    </div>
                                    <p class="post-category">{{ noti.categoria_noticia }}</p>
                                    <h2 class="title" >
                                        {{ noti.titulo }}
                                    </h2>
                                    <div class="d-flex align-items-center">
                                        <img src="{{ noti.autor.profile_picture.url }}" alt="" class="img-fluid post-author-img flex-shrink-0">
                                        <div class="post-meta">
                                            <p class="post-author-list">{{ noti.author }}</p>
                                            <p class="post-date">
                                                <time datetime="{{ noti.fecha_de_publicacion }}">{{ noti.fecha_de_publicacion|date:"d F, Y" }}</time>
                                            </p>
                                        </div>
                                    </div>
                                </article>
                            </a>
                        </div>
                    {% empty %}
                        <p>No se han publicado noticias todavía.</p>
                    {% endfor %}
                </div>
            </div>
        
            <div class="blog-pagination">
                <ul class="justify-content-center">
                  <li><a href="#">1</a></li>
                  <li class="active"><a href="#">2</a></li>
                  <li><a href="#">3</a></li>
                </ul>
              </div><!-- End blog pagination -->
      
            </div>
          </section><!-- End Blog Section -->

          
        
        
      
                {% comment %} <div class="col-xl-4 col-md-6">
                  <article>
      
                    <div class="post-img">
                      <img src="assets/img/blog/blog-2.jpg" alt="" class="img-fluid">
                    </div>
      
                    <p class="post-category">Sports</p>
      
                    <h2 class="title">
                      <a href="blog-details.html">Nisi magni odit consequatur autem nulla dolorem</a>
                    </h2>
      
                    <div class="d-flex align-items-center">
                      <img src="assets/img/blog/blog-author-2.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
                      <div class="post-meta">
                        <p class="post-author-list">Allisa Mayer</p>
                        <p class="post-date">
                          <time datetime="2022-01-01">Jun 5, 2022</time>
                        </p>
                      </div>
                    </div>
      
                  </article>
                </div><!-- End post list item -->
      
                <div class="col-xl-4 col-md-6">
                  <article>
      
                    <div class="post-img">
                      <img src="assets/img/blog/blog-3.jpg" alt="" class="img-fluid">
                    </div>
      
                    <p class="post-category">Entertainment</p>
      
                    <h2 class="title">
                      <a href="blog-details.html">Possimus soluta ut id suscipit ea ut in quo quia et soluta</a>
                    </h2>
      
                    <div class="d-flex align-items-center">
                      <img src="assets/img/blog/blog-author-3.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
                      <div class="post-meta">
                        <p class="post-author-list">Mark Dower</p>
                        <p class="post-date">
                          <time datetime="2022-01-01">Jun 22, 2022</time>
                        </p>
                      </div>
                    </div>
      
                  </article>
                </div><!-- End post list item -->
      
                <div class="col-xl-4 col-md-6">
                  <article>
      
                    <div class="post-img">
                      <img src="assets/img/blog/blog-4.jpg" alt="" class="img-fluid">
                    </div>
      
                    <p class="post-category">Sports</p>
      
                    <h2 class="title">
                      <a href="blog-details.html">Non rem rerum nam cum quo minus olor distincti</a>
                    </h2>
      
                    <div class="d-flex align-items-center">
                      <img src="assets/img/blog/blog-author-4.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
                      <div class="post-meta">
                        <p class="post-author-list">Lisa Neymar</p>
                        <p class="post-date">
                          <time datetime="2022-01-01">Jun 30, 2022</time>
                        </p>
                      </div>
                    </div>
      
                  </article>
                </div><!-- End post list item -->
      
                <div class="col-xl-4 col-md-6">
                  <article>
      
                    <div class="post-img">
                      <img src="assets/img/blog/blog-5.jpg" alt="" class="img-fluid">
                    </div>
      
                    <p class="post-category">Politics</p>
      
                    <h2 class="title">
                      <a href="blog-details.html">Accusamus quaerat aliquam qui debitis facilis consequatur</a>
                    </h2>
      
                    <div class="d-flex align-items-center">
                      <img src="assets/img/blog/blog-author-5.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
                      <div class="post-meta">
                        <p class="post-author-list">Denis Peterson</p>
                        <p class="post-date">
                          <time datetime="2022-01-01">Jan 30, 2022</time>
                        </p>
                      </div>
                    </div>
      
                  </article>
                </div><!-- End post list item -->
      
                <div class="col-xl-4 col-md-6">
                  <article>
      
                    <div class="post-img">
                      <img src="assets/img/blog/blog-6.jpg" alt="" class="img-fluid">
                    </div>
      
                    <p class="post-category">Entertainment</p>
      
                    <h2 class="title">
                      <a href="blog-details.html">Distinctio provident quibusdam numquam aperiam aut</a>
                    </h2>
      
                    <div class="d-flex align-items-center">
                      <img src="assets/img/blog/blog-author-6.jpg" alt="" class="img-fluid post-author-img flex-shrink-0">
                      <div class="post-meta">
                        <p class="post-author-list">Mika Lendon</p>
                        <p class="post-date">
                          <time datetime="2022-01-01">Feb 14, 2022</time>
                        </p>
                      </div>
                    </div>
      
                  </article>
                </div><!-- End post list item -->
      
              </div><!-- End blog posts list --> {% endcomment %}
    

 
    {% comment %} {% for noti in noticias %}
        {% if noti.imagen %}
            <img src="{{ noti.imagen.url }}" width="50">
        {% endif %}
            <p><a href="{% url 'noticias:detalle' noti.pk %}">TITULO: {{ noti.titulo }}</a></p>
            <p>FECHA: {{ noti.fecha_de_publicacion }}</p>
            <p>CATEGORIA: {{ noti.categoria_noticia }}</p>
            <p>CONTENIDO: {{ noti.contenido }}</p>
    {% endfor %} {% endcomment %}

{% endblock contenido %}

templates/noticias/listarNoticia.html
{% extends 'base.html' %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/listar.css' %}">
</head>

{% block contenido %}
    {% if object_list %}
                    
        {% for p in object_list %}

        <h1>{{p.titulo}}</h1>
        {{p.contenido|safe}}
        <p>{{p.fecha_de_publicacion}}</p>

        {% endfor %}

    {% else %}
        <h1>no hay noticias :</h1>
    {% endif %}
{% endblock contenido %}